/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Tab to open
 */
export type Tab = File | Launcher;
/**
 * Path to the file/notebook to open as a tab
 */
export type Path = string;
/**
 * Type of the tab
 */
export type Type = 'file';
/**
 * Type of the tab
 */
export type Type1 = 'launcher';
/**
 * Series of two or more tabs
 */
export type ListOfTabsToUseInScenario = Tab[];

export interface TabScenarioOptions {
  tabs: ListOfTabsToUseInScenario;
  [k: string]: any;
}
export interface File {
  path?: Path;
  type: Type;
  [k: string]: any;
}
export interface Launcher {
  type: Type1;
  [k: string]: any;
}
