/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Location of file/notebook to open. If empty opens a new launcher.
 */
export type Path = string;
/**
 * Series of two or more tabs
 */
export type ListOfTabsToUseInScenario = Tab[];

export interface TabScenarioOptions {
  tabs: ListOfTabsToUseInScenario;
  [k: string]: any;
}
/**
 * Tab to open
 */
export interface Tab {
  path?: Path;
  [k: string]: any;
}
