/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Number of pixes to scroll by
 */
export type ScrollFromTop = number;
/**
 * Behavior of scroll, either 'smooth' for smooth scrolling, or 'auto' for instant scrolling.
 */
export type ScrollBehaviour = 'smooth' | 'auto';
/**
 * Instead of scrolling, traverse notebook cell-by-cell (which also combines stepwise scrolling and cell activation/deactivation). Small number of cells (50-100) is recommended for benchmarking such scenario. 'scrollTop' and 'scrollBehavior' have no effect if this variant is enabled. Has no effect in file editor.
 */
export type TraverseCellByCell = boolean;
/**
 * Editor widget to test completion in
 */
export type EditorType = 'Notebook' | 'File Editor';
/**
 * Optional path to an existing document of specified editor type. When empty (default) a new temporary file will be created.
 */
export type PathToDocument = string;
/**
 * If using a notebook, how many cell should be created? For file editor, how many lines?
 */
export type NumberOfCellsBlocksToAppend = number;
/**
 * Text to populate editors/cells with.
 */
export type EditorCellContent = string;

export interface ScrollScenarioOptions {
  scrollTop: ScrollFromTop;
  scrollBehavior: ScrollBehaviour;
  cellByCell?: TraverseCellByCell;
  editor: EditorType;
  path?: PathToDocument;
  cells: NumberOfCellsBlocksToAppend;
  editorContent?: EditorCellContent;
}
