/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Python code cells to execute one-by-one to populate the debugger namespace, e.g. `from numpy import *`
 */
export type CodeToExecute = string[];
/**
 * The scenario waits until debugger panel is populated with at least as many variables as specified. For accurate timings should have as many members as there are code cells.
 */
export type ExpectedNumberOfVariables = number[];

export interface DebuggerScenarioOptions {
  codeCells: CodeToExecute;
  expectedNumberOfVariables: ExpectedNumberOfVariables;
}
