/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Editor widget to test cell creation in
 */
export type WidgetType = 'Notebook';
/**
 * Optional path to an existing document of specified editor type. When empty (default) a new temporary file will be created.
 */
export type PathToDocument = string;
/**
 * If using a notebook, how many cell should be created? For file editor, how many lines?
 */
export type NumberOfCellsBlocksToAppend = number;
/**
 * Text to populate editors/cells with.
 */
export type EditorCellContent = string;
export type CellType = 'code' | 'markdown' | 'raw';
/**
 * Where to attach the editor widget in the layout
 */
export type WidgetPositionInTheLayout =
  | 'split-top'
  | 'split-left'
  | 'split-right'
  | 'split-bottom'
  | 'tab-before'
  | 'tab-after';

export interface CreateCellsScenarioOptions {
  editor: WidgetType;
  path?: PathToDocument;
  cells: NumberOfCellsBlocksToAppend;
  editorContent?: EditorCellContent;
  cellType?: CellType;
  widgetPosition?: WidgetPositionInTheLayout;
}
