/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Command ID
 */
export type Command1 = string;
/**
 * Commands used for scenario setup
 */
export type SetupCommands = Command[];
/**
 * Commands used for scenario profiling/benchmarking
 */
export type CommandsToExecute = Command[];
/**
 * Commands used for scenario cleanup
 */
export type CleanupCommands = Command[];

export interface CustomScenarioOptions {
  setupCommands: SetupCommands;
  commands: CommandsToExecute;
  cleanupCommands: CleanupCommands;
  [k: string]: any;
}
/**
 * Command to execute
 */
export interface Command {
  id: Command1;
  args: Arguments;
  [k: string]: any;
}
/**
 * Command arguments
 */
export interface Arguments {
  [k: string]: any;
}
